#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -euo pipefail

sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko -- --mode disko "$SCRIPTPATH/disko.nix"
