#!/usr/bin/env bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

[[ "${VERBOSE:-0}" -eq 1 ]] && set -v
[[ "${DEBUG:-0}" -eq 1 ]] && set -x

set -euo pipefail

eval "$(direnv stdlib)"

VERB="$1"
TARGET="$SCRIPTPATH/$VERB"
RUNNER="$TARGET/runner"
if [[ -f "$RUNNER" ]]; then
  exec "$RUNNER" "$@"
else
  log_error "$RUNNER is unimplemented."
  exit 1
fi
